#!/usr/bin/env python3
# % Name :
# %   gen_iono_grid_3d.m
# %
# % Purpose :
# %   Generates ionospheric plasma density, collision frequency and irregularity
# %   grid as a function of range and height using IRI. Gridded geomagnetic
# %   field data (generated using IGRF) is also returned. The format of the
# %   outputs is that required for input into the 3d raytracing engine.
# %
# % Calling sequence :
# %   1. [iono_pf_grid, iono_pf_grid_5, collision_freq, Bx, By, Bz] = ...
# %         gen_iono_grid_3d(UT, R12, iono_grid_parms, geomag_grid_parms, ...
# %                          doppler_flag)
# %
# %   2. [iono_pf_grid, iono_pf_grid_5, collision_freq, Bx, By, Bz] = ...
# %         gen_iono_grid_3d(UT, R12, iono_grid_parms, geomag_grid_parms, ...
# %                          doppler_flag, profile_type)
# %
# %   3. [iono_pf_grid, iono_pf_grid_5, collision_freq, Bx, By, Bz] = ...
# %         gen_iono_grid_3d(UT, R12, iono_grid_parms, geomag_grid_parms, ...
# %                          doppler_flag, profile_type)
# %
# % Inputs :
# %   UT                - 5x1 array containing UTC date and time - year, month,
# %                         day, hour, minute
# %   R12               - scalar R12 index
# %      R12 = 1 - 200 :  IRI is called with R12 (Zurich V1.0) input as the
# %                       user specified yearly smoothed monthly median sunspot
# %                       number.  
# %      R12 = -1      :  IRI is called with ionospheric conditions (R12,
# %                       IG12, and F10.7) read from file (ig_rz.dat) based on
# %                       input epoch (UT) and may be historical or projected
# %                       conditions (dependent on the epoch). 
# %
# %   iono_grid_parms   - 9x1 vector containing the parameters which define the
# %                       ionospheric grid :
# %           (1) geodetic latitude (degrees) start
# %           (2) latitude step (degrees)
# %           (3) number of latitudes
# %           (4) geodetic longitude (degrees) start
# %           (5) lonitude step (degrees)
# %           (6) number of longitudes
# %           (7) geodetic height (km) start
# %           (8) height step (km)
# %           (9) number of heights
# %
# %   geomag_grid_parms - 9x1 vector containing the parameters which define the
# %                       geomagnetic grid :
# %           (1) geodetic latitude (degrees) start
# %           (2) latitude step (degrees)
# %           (3) number of latitudes
# %           (4) geodetic lonitude (degrees) start
# %           (5) longitude step (degrees)
# %           (6) number of longitudes
# %           (7) geodetic height (km) start
# %           (8) height step (km)
# %           (9) number of heights
# %
# %   doppler_flag      - flag to indicate whether (=1) or not (=0) to generate
# %                       necessary parameters for Doppler shift and spread
# %                       calculations in the raytracing routines. NB turning
# %                       this on will increase the time required to generate
# %                       the ionosphere.
# %
# % Optional Inputs
# %   profile_type      - specify how the ionospheric profiles (with height) are
# %                       to be generated (default is 'iri') (see also Notes) :
# %      'iri'           = profiles are those generated by the IRI2020 model
# %      'iri2020'       = profiles are those generated by the IRI2020 model
# %      'firi'          = profiles are those generated by the IRI2020 model
# %                        using the FIRI data for heights below 120 km, with
# %                        interpolation between FIRI and IRI F layer
# %
# %   iri_options        - structure which specfies options for IRI2020 (see 
# %                        m for details). iri_options is ignored if a
# %                        profile_type other than IRI2020 is specified.
# %
# % Outputs :
# %   iono_pf_grid   - 3d grid (height vs lat. vs lon.) of ionospheric plasma
# %                      frequency (MHz)
# %   iono_pf_grid_5 - 3d grid (height vs lat. vs lon.) of ionospheric plasma
# %                      frequency (MHz) 5 minutes later
# %   collison_freq  - 3d grid (height vs lat. vs lon.) of ionospheric
# %                      collision frequencies
# %   Bx             - 3d grid of x component of geomagnetic field
# %   By             - 3d grid of y component of geomagnetic field
# %   Bz             - 3d grid of z component of geomagnetic field
# %
# %
# % Dependencies:
# %   mex
# %   igrf2016.mex
# %   solar_za.m
# %
# % Modification History:
# %   V1.0  M.A. Cervera  25/06/2010
# %     Initial Version
# %
# %   V1.1  M.A. Cervera  12/09/2012
# %     Updated to use IRI2012 and IGRF2011
# %
# %   V1.2  M.A. Cervera  03/05/2016
# %     Updated to use IRI2020 and IGRF2016
# %
# %   V1.3  M.A. Cervera  17/09/2018
# %     Improved method for calculating the effective collision frequency using
# %     electron and temperatures (from IRI) and density of neutral constituents
# %     (from nrlmsise00). See e.g. Pederick and Cervera (2014), Radio Sci., 
# %     vol. 49, 81--93, doi:10.1002/2013RS005274
# %
# %   V1.4  M.A. Cervera 06/06/2019
# %     Removed the "Chapman" options. No longer required. Tidied up help.
# %
# %   V1.5  M.A. Cervera 24/02/2020
# %     Minor update to collision frequency calculation. Now returns NaN below
# %     altitudes where IRI returns valid electron and ion temperatures.
# %

# function [iono_pf_grid, iono_pf_grid_5, collision_freq, Bx, By, Bz] = ...
#          gen_iono_grid_3d(UT, R12, iono_grid_parms, geomag_grid_parms, ...
#                           doppler_flag, profile_type, varargin)
import numpy as np
#
import sys
from pylap.maths import enu2xyz
from pylap.maths import wgs84_xyz2llh
from pylap.maths import earth_radius_wgs84
from pylap.maths import wgs842gc_lat
from pylap.maths import raz2latlon
from pylap.maths import eff_coll_freq
from pylap.maths import iri2020_firi_interp
from pylap.dop_spread_eq import dop_spread_eq
from pylap.nrlmsise00 import nrlmsise00
from pylap.igrf2016 import igrf2016
from pylap.irreg_strength import irreg_strength
from pylap.iri2020 import iri2020


def _parfor_gmap():
    try:
        from parfor import gmap
    except ImportError as exc:
        raise RuntimeError(
            "Parallel ionosphere generation requires the 'parfor' package. "
            "Install parfor or call gen_iono_grid_3d with num_workers=1."
        ) from exc
    return gmap


def _gen_iono_lat_slice(job):
    lat_idx, lat, args = job
    iono_pf_subgrid, iono_pf_subgrid_5, collision_freq_subgrid = \
        gen_iono_subgrid(lat, *args)
    return lat_idx, iono_pf_subgrid, iono_pf_subgrid_5, collision_freq_subgrid


def _gen_bfield_lat_slice(job):
    lat_idx, lat, args = job
    bx_subgrid, by_subgrid, bz_subgrid = gen_Bfield_subgrid(lat, *args)
    return lat_idx, bx_subgrid, by_subgrid, bz_subgrid


def gen_iono_grid_3d(UT, R12, iono_grid_parms,
                     geomag_grid_parms, doppler_flag, 
                     profile_type='iri', *args, num_workers=None):
    pfsq_conv = 80.6163849431291e-12;  #% mult. factor to convert electron density
#                                      % in m^-3 to plasma freq. squared in MHz^2

#   % get the iri_options structure if it has been input
    if len(args) > 0:
        iri_options = args[0]
    else:
        iri_options = {}

    valid_profile_types = ['chapman_fllhc', 'chapman', 'iri', 'iri2020', 'firi']
    if profile_type.lower() not in valid_profile_types:
        print('invalid profile type: {}. Valid types: {}'.format(
              profile_type, valid_profile_types))
        sys.exit('gen_iono_grid_3d')
#*
    fllhc_flag = 0
    if profile_type.lower() == 'chapman_fllhc':
          profile_type = 'chapman'
          fllhc_flag = 1
          
#   % ionospheric and geomagnetic grid definition
    lat_min = iono_grid_parms[0]
    lat_inc = iono_grid_parms[1]
    num_lat = iono_grid_parms[2]
    lon_min = iono_grid_parms[3]
    lon_inc = iono_grid_parms[4]
    num_lon = iono_grid_parms[5]
    ht_min = iono_grid_parms[6]
    ht_inc = iono_grid_parms[7]
    num_ht = iono_grid_parms[8]

    B_lat_min = geomag_grid_parms[0]
    B_lat_inc = geomag_grid_parms[1]
    B_num_lat = geomag_grid_parms[2]
    B_lon_min = geomag_grid_parms[3]
    B_lon_inc = geomag_grid_parms[4]
    B_num_lon = geomag_grid_parms[5]
    B_ht_min = geomag_grid_parms[6]
    B_ht_inc = geomag_grid_parms[7]
    B_num_ht = geomag_grid_parms[8]
    
#   % initialize arrays
    iono_pf_grid = np.zeros((int(num_lat), int(num_lon), int(num_ht))) * np.nan
    iono_pf_grid = np.zeros((int(num_lat), int(num_lon), int(num_ht))) * np.nan
    iono_pf_grid_5 = np.zeros((int(num_lat), int(num_lon), int(num_ht))) * np.nan
    collision_freq = np.zeros((int(num_lat), int(num_lon), int(num_ht))) * np.nan
    Bx = np.zeros((int(B_num_lat), int(B_num_lon), int(B_num_ht)))
    By = np.zeros((int(B_num_lat), int(B_num_lon), int(B_num_ht)))
    Bz = np.zeros((int(B_num_lat), int(B_num_lon), int(B_num_ht)))

#   % generate ionospheric grids
#   %
    lat_max = lat_min + (num_lat - 1) * lat_inc
    lon_max = lon_min + (num_lon - 1) * lon_inc
    ht_max = ht_min + (num_ht - 1) * ht_inc
    if num_workers is not None and num_workers > 1:
        gmap = _parfor_gmap()
        iono_args = (
            lon_min, lon_inc, lon_max, ht_min, ht_inc, ht_max, R12, UT,
            profile_type, doppler_flag, iri_options, fllhc_flag,
        )
        iono_jobs = [
            (lat_idx, lat_min + lat_idx * lat_inc, iono_args)
            for lat_idx in range(int(num_lat))
        ]
        for lat_idx, iono_pf_subgrid, iono_pf_subgrid_5, collision_freq_subgrid in gmap(
            _gen_iono_lat_slice,
            iono_jobs,
            total=len(iono_jobs),
            n_processes=int(num_workers),
            yield_ordered=False,
            desc="Generating ionosphere",
        ):
            iono_pf_grid[lat_idx, :, :] = iono_pf_subgrid
            iono_pf_grid_5[lat_idx, :, :] = iono_pf_subgrid_5
            collision_freq[lat_idx, :, :] = collision_freq_subgrid
    else:
        for lat_idx in range(int(num_lat) - 1, -1, -1):
            lat = lat_min + lat_idx * lat_inc
            # % generate ionosphere gridded in longitude and height
            [iono_pf_subgrid, iono_pf_subgrid_5, collision_freq_subgrid] = \
            gen_iono_subgrid(lat, lon_min, lon_inc, lon_max, ht_min, ht_inc, 
                            ht_max, R12, UT, profile_type, doppler_flag, 
                            iri_options, fllhc_flag)

            # % populate the ionospheric (lat,lon,height) grids
            iono_pf_grid[lat_idx, :, :] = iono_pf_subgrid
            iono_pf_grid_5[lat_idx, :, :] = iono_pf_subgrid_5
            collision_freq[lat_idx, :, :] = collision_freq_subgrid
        
#   %
#   % generate magnetic field grids
#   %
    B_lat_max = B_lat_min + (B_num_lat - 1) * B_lat_inc
    B_lon_max = B_lon_min + (B_num_lon - 1) * B_lon_inc
    B_ht_max = B_ht_min + (B_num_ht - 1) * B_ht_inc
    if num_workers is not None and num_workers > 1:
        bfield_args = (
            B_lon_min, B_lon_inc, B_lon_max, B_ht_min, B_ht_inc, B_ht_max, UT,
        )
        bfield_jobs = [
            (B_lat_idx, B_lat_min + B_lat_idx * B_lat_inc, bfield_args)
            for B_lat_idx in range(int(B_num_lat))
        ]
        for B_lat_idx, Bx_subgrid, By_subgrid, Bz_subgrid in gmap(
            _gen_bfield_lat_slice,
            bfield_jobs,
            total=len(bfield_jobs),
            n_processes=int(num_workers),
            yield_ordered=False,
            desc="Generating geomagnetic field",
        ):
            Bx[B_lat_idx, :, :] = Bx_subgrid
            By[B_lat_idx, :, :] = By_subgrid
            Bz[B_lat_idx, :, :] = Bz_subgrid
    else:
        for B_lat_idx in range(int(B_num_lat) - 1, -1, -1): 
            lat = B_lat_min + B_lat_idx * B_lat_inc

        #% generate magnetic field gridded in longitude and height
            [Bx_subgrid, By_subgrid, Bz_subgrid] = \
	        gen_Bfield_subgrid(lat, B_lon_min, B_lon_inc, B_lon_max, 
	                       B_ht_min, B_ht_inc, B_ht_max, UT)

        #% populate the magnetic field (lat,lon,height) grids
            Bx[B_lat_idx, :, :] = Bx_subgrid
            By[B_lat_idx, :, :] = By_subgrid
            Bz[B_lat_idx, :, :] = Bz_subgrid

    return iono_pf_grid, iono_pf_grid_5, collision_freq, Bx, By, Bz

# %
# % subfunction which generates geomagnetic field gridded over longitude and
# % height for a given input latitude
# %
def gen_Bfield_subgrid(lat, B_lon_min, B_lon_inc, B_lon_max, 
		                   B_ht_min, B_ht_inc, B_ht_max, UT):
    num_lon = round((B_lon_max - B_lon_min) / B_lon_inc) + 1
    num_height = round((B_ht_max - B_ht_min) / B_ht_inc) + 1
    lon_values = B_lon_min + np.arange(num_lon) * B_lon_inc
    height_values = B_ht_min + np.arange(num_height) * B_ht_inc
    sizeX = len(lon_values)
    sizeY = len(height_values)
    Bx_subgrid = np.zeros((sizeX, sizeY))
    By_subgrid = np.zeros((sizeX, sizeY))
    Bz_subgrid = np.zeros((sizeX, sizeY))
    
    for lon_idx, lon in enumerate(lon_values):
        for ht_idx, height in enumerate(height_values):
            mag_field = igrf2016(lat, lon, UT, height)
            field_N = mag_field[0]
            field_E = mag_field[1]
            field_U = -mag_field[2]
            [field_x, field_y, field_z] = enu2xyz.ENU2xyz(field_E, field_N, field_U, 
	                                    lat, lon)

            Bx_subgrid[lon_idx][ht_idx] = field_x
            By_subgrid[lon_idx][ht_idx] = field_y
            Bz_subgrid[lon_idx][ht_idx] = field_z

    return Bx_subgrid, By_subgrid, Bz_subgrid

# %
# % subfunction which generates ionospheric data gridded over longitude and
# % height for a given input latitude
def gen_iono_subgrid(lat, lon_min, lon_inc, lon_max, ht_min, ht_inc, 
                        ht_max, R12, UT, profile_type, doppler_flag, 
                        iri_options, fllhc_flag):
    pfsq_conv = 80.6163849431291e-12;    #% multiplicative factor to convert 
#                                        % electron dens (m^3) to 
#                                        % plasma freq. squared (MHz^2)

    height_arr = np.arange(ht_min, ht_max+ht_inc, ht_inc, dtype = float)
    lat_arr = lat * np.ones_like(height_arr) 

#M UT 5 minutes later*
    UT_5 = UT[:] 
    UT_5[4] = UT_5[4] + 5
    if UT_5[4] > 59:
        UT_5[4] = UT_5[4] - 60
        UT_5[3] = UT_5[3] + 1
    if UT_5[3] > 23: 
        UT_5[3] = 0 

    lon_values = np.arange(lon_min, lon_max + lon_inc / 2, lon_inc)
    num_lon = len(lon_values)
    num_heights = height_arr.size
    iono_pf_subgrid = np.zeros((num_lon, num_heights))
    iono_pf_subgrid_5 = np.zeros((num_lon, num_heights))
    collision_freq_subgrid = np.zeros((num_lon, num_heights))
    for lon_idx, lon in enumerate(lon_values):
        lon_arr = np.ones_like(height_arr) *lon
        
#     %%%%%%%%%%%%%%%%%%%
#     % This is IRI2020 %#     %%%%%%%%%%%%%%%%%%%
        if profile_type.lower() == 'iri' or \
            profile_type.lower() ==  'iri2020': 

            num_heights = round((ht_max - ht_min)/ht_inc) + 1
#       % call IRI2020
            [iono, iono_extra] = iri2020(lat, lon, R12, UT, ht_min, ht_inc, 
 	                           num_heights, iri_options)

            if doppler_flag:
                [iono5, iono_extra5] = iri2020(lat, lon, R12, UT_5, ht_min, ht_inc, 
 	                               num_heights, iri_options)
#       % get the electron density (Num electrons per m^3)
            elec_dens = iono[0][:]
            elec_dens[elec_dens == -1] = 0

            if doppler_flag:
                elec_dens5 = iono5[0] 
                elec_dens5[elec_dens5 == -1] = 0
            
#       % calculate plasma frequency (MHz) profile and fill the array
            
            iono_pf_subgrid[lon_idx] = np.sqrt(elec_dens * pfsq_conv); 
            if doppler_flag:
                iono_pf_subgrid_5[lon_idx] = np.sqrt(elec_dens5 * pfsq_conv)  
            else:
                iono_pf_subgrid_5[lon_idx] = np.sqrt(elec_dens * pfsq_conv)

#       % electron and ion temperatures
            T_e = iono[3]
            T_e[T_e == -1] = np.nan

            T_ion = iono[2]
            T_ion[T_ion == -1] = np.nan
#       % neutral densities
            if (R12 == -1):
                [neutral_dens, temp] = nrlmsise00(lat_arr, lon_arr, height_arr, UT)
            else:
# 	% calculate f10.7 : see Davies, "Ionospheric Radio", 1990, pp442
                f107 = 63.75 + R12*(0.728 + R12*0.00089)
                [neutral_dens, temp] = \
                nrlmsise00(lat_arr, lon_arr, height_arr, UT, f107, f107, 4)

#       % calculate collision frequency
            collision_freq_subgrid[lon_idx,:] = \
            eff_coll_freq.eff_coll_freq(T_e, T_ion, elec_dens, neutral_dens)
#     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#     % This is IRI2020 with FIRI option on %
#     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        elif profile_type.lower() == 'firi':

            num_heights = round((ht_max - ht_min)/ht_inc) + 1

#       % call IRI2020 with FIRI option on
            [iono, iono_extra] = iri2020_firi_interp.iri2020_firi_interp(lat, lon, R12, UT, ht_min, ht_inc,
	        num_heights, iri_options)

            if doppler_flag:
                [iono5, iono_extra5] = iri2020_firi_interp.iri2020_firi_interp(lat, lon, R12, UT_5, ht_min, ht_inc,
	            num_heights, iri_options)
#           end
#           % get the electron density (Num electrons per m^3)
            elec_dens = iono[0][:]
            elec_dens[elec_dens == -1] = 0

            if doppler_flag:
                elec_dens5 = iono5[0,:]
                elec_dens5[elec_dens == -1] = 0

#       % calculate plasma frequency (MHz) profile and fill the array
            iono_pf_subgrid[lon_idx] = np.sqrt(elec_dens * pfsq_conv); 
            if doppler_flag:
                iono_pf_subgrid_5[lon_idx] = np.sqrt(elec_dens5 * pfsq_conv)  
            else:
                iono_pf_subgrid_5[lon_idx] = np.sqrt(elec_dens * pfsq_conv)

#       % electron and ion temperatures

            T_e = iono[3]
            T_e[T_e == -1] = np.nan

            T_ion = iono[2]
            T_ion[T_ion == -1] = np.nan
            
            # % neutral densities
            if (R12 == -1):
                [neutral_dens, temp] = nrlmsise00(lat_arr, lon_arr, height_arr, UT)
            else:
    # 	% calculate f10.7 : see Davies, "Ionospheric Radio", 1990, pp442
                f107 = 63.75 + R12*(0.728 + R12*0.00089)
                [neutral_dens, temp] = \
                nrlmsise00(lat_arr, lon_arr, height_arr, UT, f107, f107, 4)

    #       % calculate collision frequency
                collision_freq_subgrid[lon_idx,:] = \
                eff_coll_freq.eff_coll_freq(T_e, T_ion, elec_dens, neutral_dens)

 
    return iono_pf_subgrid, iono_pf_subgrid_5, collision_freq_subgrid
